version: '3.8'

# Development infrastructure only
# Run with: make dev
#
# This starts only Postgres + MinIO in Docker.
# Rust API and SvelteKit web run natively on your Mac for:
#   - Fast hot reload
#   - Natural networking (iPhone can connect)
#   - Standard debugging tools

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ariata-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ariata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-schemas.sh:/docker-entrypoint-initdb.d/init-schemas.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: ariata-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  minio_data:
